# Generated by Django 5.0.4 on 2024-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220)),
                ('url_durmazz', models.URLField()),
                ('url_beyaz', models.URLField()),
                ('durmazz_price', models.FloatField(blank=True)),
                ('beyaz_price', models.FloatField(blank=True)),
                ('price_difference', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('LA', 'Laptops'), ('HM', 'Home Appliances'), ('PH', 'Phones'), ('TS', 'Televisions and sound'), ('PR', 'Peripherials'), ('GP', 'Gaming Products')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
            options={
                'ordering': ('name', 'price_difference'),
            },
        ),
    ]
