# Generated by Django 5.0.4 on 2024-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='link',
            name='price_difference',
        ),
        migrations.AlterField(
            model_name='link',
            name='durmazz_price',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
