# Generated by Django 5.0.4 on 2024-06-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='durmazz_price',
            new_name='boravin_price',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='url_durmazz',
            new_name='url_boravin',
        ),
    ]
