# Generated by Django 5.0.4 on 2024-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_durmazz_price_link_boravin_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='price_difference',
            field=models.FloatField(default=0),
        ),
    ]
